    - name: Pull latest calculator image
      community.docker.docker_image:
        name: gokulshivaav/calculator-app
        tag: latest
        source: pull

    - name: Remove old container if exists
      community.docker.docker_container:
        name: calculator
        state: absent

    - name: Run calculator container
      community.docker.docker_container:
        name: calculator
        image: gokulshivaav/calculator-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
